sudo: required
dist: trusty
language: node_js
node_js:
  - '9.5.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g angular-cli
- npm install -g karma
- npm install
- npm build

script: karma start karma.conf.js --single-run

befor_deploy:
  - ls

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: dist
  acl: public_read
  on:
      branch: feature/setup-travis